### ISSUE TITLE
Suggestions from morning review

### ISSUE THREAD

**Issue by RayhanTabase** [thecodechaser/portfolio#9]
I think adding a little padding to the cards will make the project look better besides that everything looks great.

**Comment by thecodechaser** [comment]
> I think adding a little padding to the cards will make the project look better besides that everything looks great.

Hello @RayhanTabase 👋 
Thank you for your suggestions to make changes in that padding for cards, And you are probably correct, That will make my project more improve. I will definitely look into these changes.

**Comment by NataliaPoletaeva** [comment]
Good job on your project! Keep up the good work :) However, there are several things that need to be adressed before moving on.

- Think about choosing more descriptive names for the classes as if you're going to work together with somebody, they might get confused.
- Mind using responsive measurement units so that your project would function exactly how you want 🎉

**Comment by AnselemOdims** [comment]
Nice work so far!

## Suggestions
- You can use only one button event listener instead of adding one to every button
- When you hover over the card images, they overflow from the card. I think it might be better to keep them within the card even in hover state
- I think the headline section background image will look better if it contains the whole width
- I think the site will more interactive if it is responsive both on mobile, tablet and desktop
- I think the number of cards can be increased to four to match the template

**Comment by thecodechaser** [comment]
> Good job on your project! Keep up the good work :) However, there are several things that need to be adressed before moving on.
> 
> * Think about choosing more descriptive names for the classes as if you're going to work together with somebody, they might get confused.
> * Mind using responsive measurement units so that your project would function exactly how you want 🎉

Hii @NataliaPoletaeva 👋 
Thank you for your suggestions, I will work on these and test I think it will make my code more readable for other developers.

**Comment by thecodechaser** [comment]
> Nice work so far!
> 
> ## Suggestions
> * You can use only one button event listener instead of adding one to every button
> * When you hover over the card images, they overflow from the card. I think it might be better to keep them within the card even in hover state
> * I think the headline section background image will look better if it contains the whole width
> * I think the site will more interactive if it is responsive both on mobile, tablet and desktop
> * I think the number of cards can be increased to four to match the template

**Comment by thecodechaser** [comment]
> Nice work so far!
> 
> ## Suggestions
> * You can use only one button event listener instead of adding one to every button
> * When you hover over the card images, they overflow from the card. I think it might be better to keep them within the card even in hover state
> * I think the headline section background image will look better if it contains the whole width
> * I think the site will more interactive if it is responsive both on mobile, tablet and desktop
> * I think the number of cards can be increased to four to match the template

Hello @AnselemOdims 👋 
Thank you for your detailed review, I will definitely work on these changes to improve my projects.
